In [2]:
import pandas as pd
df=pd.read_excel("Cleaned Dataset for Data Analytics.xlsx")
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,No Coupon Code,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [4]:
import sqlite3
conn=sqlite3.connect("Sales.db")
df.to_sql(name='sales',con=conn,if_exists='replace',index=False)
print("Dataset imported successfully")

Dataset imported successfully

In [5]:
query="""SELECT * FROM sales LIMIT 5"""
result=pd.read_sql(query,conn)
result

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [13]:
query1="""
SELECT CustomerID,OrderStatus
FROM sales
WHERE PaymentMethod='Online'
"""
result1=pd.read_sql(query1,conn)
result1

    CustomerID OrderStatus
0       C75739     Shipped
1       C81840   Delivered
2       C93861    Returned
3       C34416     Pending
4       C17470   Delivered
..         ...         ...
253     C82921     Shipped
254     C70246     Pending
255     C72007     Pending
256     C20095   Cancelled
257     C79674   Delivered

[258 rows x 2 columns]

In [12]:
query2 = """
SELECT OrderID, Product, TotalPrice
FROM sales
ORDER BY TotalPrice
"""
result2 = pd.read_sql(query2, conn)
result2

        OrderID  Product  TotalPrice
0     ORD201161    Phone       11.39
1     ORD200863    Phone       14.06
2     ORD200240   Tablet       17.24
3     ORD200542   Tablet       17.98
4     ORD200336   Laptop       18.20
...         ...      ...         ...
1195  ORD200328   Tablet     3370.20
1196  ORD200469    Chair     3384.90
1197  ORD200632   Laptop     3390.80
1198  ORD201122  Monitor     3390.95
1199  ORD200789   Tablet     3456.40

[1200 rows x 3 columns]

In [18]:
query3="""
SELECT SUM(TotalPrice) AS Total_Revenue
FROM sales
"""
result3=pd.read_sql(query3,conn)
result3

   Total_Revenue
0     1264761.96

In [17]:
query4="""
SELECT AVG(TotalPrice) AS Average_Revenue
FROM sales
"""
result4=pd.read_sql(query4,conn)
result4

   Average_Revenue
0        1053.9683

In [5]:
query5="""
SELECT COUNT(*) as Total_orders
FROM sales
"""
result5=pd.read_sql(query5,conn)
result5

   Total_orders
0          1200

In [6]:
query6="""
SELECT Product,SUM(Quantity) AS Total_Quantity
FROM sales
GROUP BY Product
"""
result6=pd.read_sql(query6,conn)
result6

   Product  Total_Quantity
0    Chair             562
1     Desk             508
2   Laptop             535
3  Monitor             480
4    Phone             411
5  Printer             542
6   Tablet             497

In [7]:
conn.close()