In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("Cleaned Dataset for Data Analytics.xlsx")
df

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,No Coupon Code,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [3]:
#Display the dataset information
df.info()

#dataset shape
print(f"Dataset Shape: {df.shape}")

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 131.4 KB
Dataset Shape: (1200, 14)

In [8]:
#Statistics
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [4]:
numerical_cols=df.select_dtypes(include=['int64','float64']).columns
print(numerical_cols)

Index(['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice'], dtype='str')

In [5]:
print("Mean:")
print(df[numerical_cols].mean())

Mean:
Quantity          2.945833
UnitPrice       356.412750
ItemsInCart       5.485000
TotalPrice     1053.968300
dtype: float64

In [6]:
print("Count:")
print(df.count())

Count:
OrderID            1200
Date               1200
CustomerID         1200
Product            1200
Quantity           1200
UnitPrice          1200
ShippingAddress    1200
PaymentMethod      1200
OrderStatus        1200
TrackingNumber     1200
ItemsInCart        1200
CouponCode         1200
ReferralSource     1200
TotalPrice         1200
dtype: int64

In [7]:
print("Median:")
print(df[numerical_cols].median())

Median:
Quantity         3.000
UnitPrice      364.210
ItemsInCart      5.000
TotalPrice     823.615
dtype: float64

In [14]:
categorical_cols=df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df[col].value_counts())

Column: OrderID
OrderID
ORD200000    1
ORD200001    1
ORD200002    1
ORD200003    1
ORD200004    1
            ..
ORD201195    1
ORD201196    1
ORD201197    1
ORD201198    1
ORD201199    1
Name: count, Length: 1200, dtype: int64

Column: CustomerID
CustomerID
C98474    2
C97593    2
C14847    2
C38840    2
C91155    2
         ..
C21126    1
C20095    1
C79674    1
C64753    1
C57502    1
Name: count, Length: 1189, dtype: int64

Column: Product
Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64

Column: ShippingAddress
ShippingAddress
533 Main St    8
895 Main St    6
146 Main St    5
636 Main St    5
562 Main St    5
              ..
149 Main St    1
754 Main St    1
392 Main St    1
509 Main St    1
201 Main St    1
Name: count, Length: 655, dtype: int64

Column: PaymentMethod
PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64

Column: OrderStatus
OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

Column: TrackingNumber
TrackingNumber
TRK37947903    1
TRK91186779    1
TRK42903982    1
TRK62788070    1
TRK29241424    1
              ..
TRK38009181    1
TRK69207593    1
TRK88039356    1
TRK71683331    1
TRK51116746    1
Name: count, Length: 1200, dtype: int64

Column: CouponCode
CouponCode
FREESHIP          313
No Coupon Code    309
WINTER15          292
SAVE10            286
Name: count, dtype: int64

Column: ReferralSource
ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64

In [15]:
print("\nOutlier Detection:")
Q1 = df['TotalPrice'].quantile(0.25)
Q3 = df['TotalPrice'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['TotalPrice'] < lower_bound) | (df['TotalPrice'] > upper_bound)]
print(f"{'TotalPrice'}: {len(outliers)} outliers")
print(outliers[['Product','Quantity','TotalPrice']])

Outlier Detection:
TotalPrice: 8 outliers
      Product  Quantity  TotalPrice
107   Printer         5     3353.75
326    Laptop         5     3352.40
328    Tablet         5     3370.20
469     Chair         5     3384.90
632    Laptop         5     3390.80
789    Tablet         5     3456.40
1065  Printer         5     3334.00
1122  Monitor         5     3390.95

In [16]:
# Calculate total quantity sold for each product
product_sales = df.groupby('Product')['Quantity'].sum().reset_index()

# Display product-wise sales quantity
print(product_sales)

   Product  Quantity
0    Chair       562
1     Desk       508
2   Laptop       535
3  Monitor       480
4    Phone       411
5  Printer       542
6   Tablet       497

In [17]:
# Calculate daily sales trend
daily_sales = df.groupby('Date')['TotalPrice'].sum()

# Display daily sales trend
print("Daily Sales Trend:\n",daily_sales)

Daily Sales Trend:
 Date
2023-01-01    2021.11
2023-01-02    1323.55
2023-01-03     897.70
2023-01-04    3629.54
2023-01-05    3642.30
               ...
2025-06-24    6358.22
2025-06-25     391.83
2025-06-27    1764.15
2025-06-28    3894.68
2025-06-30     505.47
Name: TotalPrice, Length: 671, dtype: float64

In [18]:
# Extract month from Date
df['Month'] = df['Date'].dt.to_period('M')

# Calculate monthly sales
monthly_sales = df.groupby('Month')['TotalPrice'].sum()

# Display monthly sales
print(monthly_sales)

Month
2023-01    56685.75
2023-02    40117.66
2023-03    48609.37
2023-04    27751.71
2023-05    63836.84
2023-06    49500.19
2023-07    42820.66
2023-08    54352.14
2023-09    29526.67
2023-10    52607.85
2023-11    43079.67
2023-12    43754.73
2024-01    38528.08
2024-02    36909.57
2024-03    36030.90
2024-04    49613.14
2024-05    27909.11
2024-06    68068.54
2024-07    42963.98
2024-08    31991.07
2024-09    39794.98
2024-10    37226.97
2024-11    32413.76
2024-12    38785.77
2025-01    29099.40
2025-02    35317.55
2025-03    39200.66
2025-04    31821.20
2025-05    43396.64
2025-06    53047.40
Freq: M, Name: TotalPrice, dtype: float64

In [25]:
#Count orders per month
monthly_orders = df.groupby('Month')['OrderID'].count()
#Display monthly order counts
print(monthly_orders)

Month
2023-01    47
2023-02    37
2023-03    43
2023-04    31
2023-05    49
2023-06    45
2023-07    44
2023-08    51
2023-09    29
2023-10    47
2023-11    41
2023-12    46
2024-01    32
2024-02    32
2024-03    36
2024-04    50
2024-05    34
2024-06    53
2024-07    43
2024-08    28
2024-09    44
2024-10    31
2024-11    35
2024-12    41
2025-01    27
2025-02    37
2025-03    49
2025-04    32
2025-05    37
2025-06    49
Freq: M, Name: OrderID, dtype: int64

In [20]:
# Payment Method Distribution
payment_method = df['PaymentMethod'].value_counts()

print(payment_method)

PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64

In [21]:
# Order Status Distribution
order_status = df['OrderStatus'].value_counts()

print(order_status)

OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

In [22]:
print("\nKey Observations:")
print("1.Numerical statistics such as mean and median calculated.")
print("2.Detected outliers in TotalPrice using IQR.")
print("3.Identified top-selling products.")
print("4.Analyzed daily and monthly sales trends.")
print("5.Examined monthly order patterns.")
print("6.Generated business insights from the dataset.")

Key Observations:
1.Numerical statistics such as mean and median calculated.
2.Detected outliers in TotalPrice using IQR.
3.Identified top-selling products.
4.Analyzed daily and monthly sales trends.
5.Examined monthly order patterns.
6.Generated business insights from the dataset.